name: Debug

on:
  release:
    types: [published]
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - run: |
          if [[ "${{github.event_name}}" == "release" || "${{github.event_name}}" == "prerelease" ]]; then
            echo "TARGET_TAG_PREFIX=" >> $GITHUB_ENV
          else
            echo "TARGET_TAG_PREFIX=dev-" >> $GITHUB_ENV
          fi

      - name: Get variables (test)
        run: |
          echo $TARGET_TAG_PREFIX
          echo ${TARGET_TAG_PREFIX}

      - name: Debug variables
        run: |
          echo github.event_name: "${{ github.event_name }}"
          echo github.event_path: "${{ github.event_path }}"
          echo github.head_ref: "${{ github.head_ref }}"
          echo github.ref_name: "${{ github.ref_name }}"
          echo github.ref: "${{ github.ref }}"
          echo github.base_ref: "${{ github.base_ref }}"
          echo github.actor: "${{ github.actor }}"
