name: Docker Image

on:
  release:
    types: [published]
  pull_request:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: rboonzaijer
  IMAGE_NAME: mysticeragames/makeitstatic-cms

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t ${{ env.IMAGE_NAME }}:build .

      - name: Test
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:build php bin/phpunit

      - name: Push non-release
        if: github.event.release.type != 'published'
        env:
          TARGET_IMAGE: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        run: |
          docker tag ${{ env.IMAGE_NAME }}:build ${{ env.TARGET_IMAGE }}
          docker push ${{ env.TARGET_IMAGE }}

      - name: Push release
        if: github.event.release.type == 'published' # (both 'released' + 'prereleased')
        env:
          TARGET_IMAGE: ${{ env.IMAGE_NAME }}:${{ github.event.release.name }}
        run: |
          docker tag ${{ env.IMAGE_NAME }}:build ${{ env.TARGET_IMAGE }}
          docker push ${{ env.TARGET_IMAGE }}

      - name: Push latest
        if: github.event.release.type == 'released'
        env:
          TARGET_IMAGE: ${{ env.IMAGE_NAME }}:latest
        run: |
          docker tag ${{ env.IMAGE_NAME }}:build ${{ env.TARGET_IMAGE }}
          docker push ${{ env.TARGET_IMAGE }}
