name: '[job] Docker image'

on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      PUSH:
        type: string
        default: 'false'
        required: true
      RELEASE:
        type: string
        default: 'false'
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      # Replace special characters with sed
      IMAGE: "mysticeragames/makeitstatic-cms:dev-$( echo ${{ github.ref_name }} | sed 's|[^a-zA-Z0-9\\.\\-\\_]|-|g' )"
      IMAGE_RELEASE: "mysticeragames/makeitstatic-cms:$( echo ${{ github.event.release.name }} | sed 's|[^a-zA-Z0-9\\.\\-\\_]|-|g' )"
      IMAGE_LATEST: mysticeragames/makeitstatic-cms:latest


    steps:

      # When using third-party actions:
      # Use a hash (hover over the commit) and not a release-version to make sure it has not been tampered with
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      # More info: https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash
    - name: Checkout
      #uses:actions/checkout@v4.2.2
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683


      # No need to use docker/login-action, it uses the same method (only silent):
      # https://github.com/docker/login-action/blob/v3.3.0/src/docker.ts#L35-L37
    - name: Docker login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u rboonzaijer --password-stdin


    - name: Docker build
      run: docker build --no-cache -t ${{ env.IMAGE }} .


    - name: Check if dependencies are available
      run: |
        COMMANDS=$'
        echo -e "\n[curl]" && \
        curl -V && \

        echo -e "\n[git]" && \
        git -v && \

        echo -e "\n[npm]" && \
        npm -v && \

        echo -e "\n[composer]" && \
        composer --version && \

        echo -e "\n[php]" && \
        php -v && \

        echo -e "\n"
        '
        docker run --rm ${{ env.IMAGE }} sh -c "${COMMANDS}" || exit 1


    - name: Run PHP codesniffer
      run: docker run --rm ${{ env.IMAGE }} php vendor/bin/phpcs


    - name: Run PHPUnit tests
      run: docker run --rm ${{ env.IMAGE }} php vendor/bin/phpunit


    - if: ${{ inputs.PUSH == 'true' }}
      name: Docker push
      run: docker push ${{ env.IMAGE }}


    - if: ${{ inputs.RELEASE == 'true' }}
      name: Docker push release
      run: |
        docker tag ${{ env.IMAGE }} ${{ env.IMAGE_RELEASE }}
        docker push ${{ env.IMAGE_RELEASE }}


    - if: ${{ inputs.RELEASE == 'true' }}
      name: Docker push latest
      run: |
        docker tag ${{ env.IMAGE }} ${{ env.IMAGE_LATEST }}
        docker push ${{ env.IMAGE_LATEST }}
  