name: PHPUnit Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2


      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: docker.io
          username: rboonzaijer
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Docker Build
        run: |
          docker build --no-cache -t local/test/image:build -f ./.docker/cms/Dockerfile .


      - name: Test
        run: |
          docker run --rm local/test/image:build php bin/phpunit
