name: PHPUnit Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2


      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: docker.io
          username: rboonzaijer
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Docker Build
        run: |
          # (temp) cms-base is not available:
          docker build --no-cache -t test:base ./.docker/cms-base
          docker build --no-cache -t test:cms --build-arg BASE_IMAGE=test --build-arg BASE_VERSION=base -f ./.docker/cms/Dockerfile .

          # docker build --no-cache -t test:cms -f ./.docker/cms/Dockerfile .


      - name: Test
        run: |
          docker run --rm test:cms php bin/phpunit
