name: PHPUnit Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: mysticeragames/makeitstatic-cms
      #volumes:
      #- /my_html:/var/www/html
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2


      - name: Test
        run: |
          pwd
          ls -la
          echo "${GITHUB_WORKSPACE}"
          #ls -la ${GITHUB_WORKSPACE}
          #cp -r -v -f ${GITHUB_WORKSPACE} /my_html

          # COPY --chown=cms ./ /var/www/html/
          # echo -e "APP_ENV=prod\nAPP_SECRET=" > /var/www/html/.env.local
          composer install --optimize-autoloader --no-interaction --no-progress
          composer run post-create-project-cmd
          php bin/phpunit
