name: Docker Image

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: rboonzaijer

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t ${{ env.IMAGE_NAME }}:build .

      - name: Test
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:build php bin/phpunit
