name: '[trigger.main] Pushed/merged to main'

on:
  push:
    branches:
      - main

jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    permissions:
      contents: read
    with:
      DOCKER_PUSH_DEV: 1
      DOCKER_PUSH_RELEASE: 0
      TARGET_IMAGE: mysticeragames/makeitstatic-cms
      DOCKERHUB_USER: rboonzaijer
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  lint-github-actions:
    uses: ./.github/workflows/job.lint-github-action.yml
    permissions:
      contents: read
