name: '[trigger.manual] Build+push cms:dev-{ref_name}'

on:
  workflow_dispatch:



jobs:
  manual:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image-makeitstatic-cms.yml@main
    with:
      PUSH: 'true'
      RELEASE: 'false'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
