name: '[trigger.pull-request] PHPUnit Tests'

on:
  pull_request:



jobs:
  pull-request:
    uses: ./.github/workflows/job.docker-image.yml
    with:
      PUSH: 'false'
      RELEASE: 'false'
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
