name: '[trigger.main] Pushed/merged to main (cms:dev-main)'

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: ./.github/workflows/job.docker-image.yml
    with:
      PUSH: 'true'
      RELEASE: 'false'
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
