name: '[trigger.release] Docker build+push release'

on:
  release:
    types:
      - released

jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    permissions:
      contents: read
    with:
      DOCKER_PUSH: 1
      DOCKER_PUSH_LATEST: 1
      TARGET_IMAGE_TAG: ${{ github.event.release.name }}
      TARGET_IMAGE_PROD: mysticeragames/makeitstatic-cms
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
