name: '[trigger.pull-request]'

on:
  pull_request:



jobs:
  docker-image:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image.yml@main
    permissions:
      contents: read
    with:
      PUSH: 'false'
      RELEASE: 'false'
      TARGET_IMAGE: 'mysticeragames/makeitstatic-cms'
      COMPOSER_TEST: 'true'
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  lint-github-actions:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.lint-github-action.yml@main
    permissions:
      contents: read
