name: '[trigger.manual] Manual Build+push'

on:
  workflow_dispatch:



jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    permissions:
      contents: read
    with:
      PUSH: 'true'
      RELEASE: 'false'
      TARGET_IMAGE: 'mysticeragames/apptest'
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
