name: '[trigger.release] RELEASE new version + latest'

on:
  release:
    types:
      - released

jobs:
  trigger-release:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image-makeitstatic-cms.yml@main
    with:
      PUSH: 'false'
      RELEASE: 'true'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
