name: '[trigger.release] Docker build+push release'

on:
  release:
    types:
      - released

jobs:
  docker-image:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image.yml@main
    permissions:
      contents: read
    with:
      PUSH: 'false'
      RELEASE: 'true'
      TARGET_IMAGE: 'mysticeragames/makeitstatic-cms'
      COMPOSER_TEST: 'true'
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
