name: '[trigger.manual] Build+push cms:dev-{ref_name}'

on:
  workflow_dispatch:



jobs:
  docker-build-push-cms-base:
    uses: ./.github/workflows/job.docker-build-push-cms-base.yml
    with:
      PUSH: 'true'
      RELEASE: 'false'
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
