name: '[trigger.manual] Manual Build+push'

on:
  workflow_dispatch:



jobs:
  docker-image:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image.yml@main
    permissions:
      contents: read
    with:
      PUSH: 'true'
      RELEASE: 'false'
      TARGET_IMAGE: 'mysticeragames/makeitstatic-cms'
      COMPOSER_TEST: 'true'
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
