name: '[trigger.manual] Manual Build+push'

on:
  workflow_dispatch:



jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    permissions:
      contents: read
    with:
      DOCKER_PUSH_DEV: 1
      DOCKER_PUSH_RELEASE: 0
      TARGET_IMAGE_CACHE_TAG: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
