name: '[trigger.pull-request]'

on:
  pull_request:



jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    with:
      DOCKER_PUSH: 0
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  lint-github-actions:
    uses: ./.github/workflows/job.lint-github-action.yml
