name: '[trigger.manual] Manual Build+push'

on:
  workflow_dispatch:



jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    permissions:
      contents: read
    with:
      DOCKER_PUSH: 1
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
