name: '[trigger.release] Docker build+push release'

on:
  release:
    types:
      - released

jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    permissions:
      contents: read
    with:
      DOCKER_PUSH_DEV: 0
      DOCKER_PUSH_RELEASE: 1
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
