name: '[trigger.main] Pushed/merged to main'

on:
  push:
    branches:
      - main

jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    with:
      DOCKER_PUSH: 1
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  lint-github-actions:
    uses: ./.github/workflows/job.lint-github-action.yml
