name: '[trigger.manual] Build+push cms:dev-{ref_name}'

on:
  workflow_dispatch:



jobs:
  manual:
    uses: ./.github/workflows/job.docker-image.yml
    with:
      PUSH: 'true'
      RELEASE: 'false'
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
