name: '[trigger.pull-request] PHPUnit Tests'

on:
  pull_request:



jobs:
  pull-request:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image-makeitstatic-cms.yml@main
    with:
      PUSH: 'false'
      RELEASE: 'false'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
