name: '[trigger.release] Docker build+push release'

on:
  release:
    types:
      - released

jobs:
  docker-image:
    uses: ./.github/workflows/job.docker-image.yml
    permissions:
      contents: read
    with:
      DOCKER_PUSH: 0
      TARGET_IMAGE_CACHE_TAG: dev-main
      TARGET_IMAGE_TAG: ${{ github.event.release.name }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
