name: '[trigger.main] Pushed/merged to main (cms:dev-main)'

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image-makeitstatic-cms.yml@main
    with:
      PUSH: 'true'
      RELEASE: 'false'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
